services:
  - type: web
    name: gih-app
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn gih.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: gih.settings
      - key: DEBUG
        value: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        sync: false
      - key: STRIPE_PUBLIC_KEY
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: CLOUDINARY_URL
        sync: false
