# Generated by Django 6.0.1 on 2026-01-30 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.EmailField(default='staff@example.com', max_length=254, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='staff',
            name='password_hash',
            field=models.CharField(default='staff@example.com', max_length=128),
            preserve_default=False,
        ),
    ]
