# Generated by Django 5.2.10 on 2026-01-30 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_guest_id_alter_housekeeping_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='time_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='time_to',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
