# Generated by ChatGPT on 2026-02-01
from django.db import migrations
import cloudinary.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_room_beds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='image',
            field=cloudinary.models.CloudinaryField(
                blank=True,
                folder='rooms',
                max_length=255,
                null=True,
                verbose_name='room-image',
            ),
        ),
    ]
