# Generated by Django 5.2.10 on 2026-02-02 13:02

import django.db.models.deletion
from django.db import migrations, models


def forwards(apps, schema_editor):
    Staff = apps.get_model('core', 'Staff')
    Role = apps.get_model('core', 'Role')
    db_alias = schema_editor.connection.alias
    # Collect distinct existing role strings from staff table
    existing_roles = set()
    for s in Staff.objects.using(db_alias).all():
        val = getattr(s, 'role', None)
        if val:
            existing_roles.add(val)
    # Create Role rows for each distinct existing role string
    for rname in existing_roles:
        # determine category: treat exact 'admin' (case-insensitive) as admin, others as staff
        cat = 'admin' if (rname and rname.strip().lower() == 'admin') else 'staff'
        Role.objects.using(db_alias).get_or_create(name=rname, defaults={'category': cat})
    # Now map staff.role (text) to role_tmp FK
    for s in Staff.objects.using(db_alias).all():
        old_role = getattr(s, 'role', None)
        if old_role:
            try:
                role_obj = Role.objects.using(db_alias).get(name=old_role)
                s.role_tmp_id = role_obj.id
                s.save()
            except Exception:
                # leave as null if no matching Role
                pass


def reverse(apps, schema_editor):
    # No easy reverse: leave as-is
    return


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_room_image_cloudinary'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('category', models.CharField(choices=[('admin', 'Admin'), ('guest', 'Guest'), ('staff', 'Staff')], default='staff', max_length=10)),
            ],
        ),
        # Add a temporary FK field which we'll populate from the existing text 'role' column,
        # then remove the old text field and rename this FK to 'role'. This avoids FK constraint
        # errors on SQLite when converting a CharField to a ForeignKey.
        migrations.AddField(
            model_name='staff',
            name='role_tmp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.role'),
        ),
        migrations.RunPython(forwards, reverse),
        migrations.RemoveField(
            model_name='staff',
            name='role',
        ),
        migrations.RenameField(
            model_name='staff',
            old_name='role_tmp',
            new_name='role',
        ),
    ]
