# Generated by Django 5.2.10 on 2026-02-02 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_update_role_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loyaltystatus',
            old_name='points_required',
            new_name='reservations_required',
        ),
        migrations.AlterField(
            model_name='guest',
            name='loyalty_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.loyaltystatus'),
        ),
        migrations.AlterField(
            model_name='loyaltystatus',
            name='name',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold')], max_length=20, unique=True),
        ),
    ]
