# Generated by Django 5.2.10 on 2026-02-05 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_guest_id_alter_housekeeping_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='loyalty_status',
        ),
        migrations.AddField(
            model_name='reservation',
            name='points_awarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reservation',
            name='points_redeemed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='used_points_discount',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='LoyaltyStatus',
        ),
    ]
